# Generated by Django 5.0.6 on 2024-06-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('imdb_id', models.CharField(blank=True, max_length=50, null=True)),
                ('download_urls', models.JSONField(blank=True, null=True)),
                ('streaming_urls', models.JSONField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('overview', models.TextField()),
                ('languages', models.JSONField()),
                ('casts', models.JSONField()),
                ('imdb_rating', models.FloatField(blank=True, null=True)),
                ('tmdb_rating', models.FloatField(blank=True, null=True)),
                ('director', models.JSONField()),
                ('genres', models.JSONField()),
                ('release_date', models.DateField()),
                ('poster_url', models.URLField()),
                ('backdrop_url', models.URLField()),
                ('production_countries', models.JSONField()),
                ('standard_user', models.BooleanField(default=False)),
                ('premium_user', models.BooleanField(default=False)),
            ],
        ),
    ]
